### ISSUE TITLE
dn init error 

### ISSUE THREAD

**Issue by lqjack** [alibaba/dawn#59]
when i build execute the command `dn init` , i get the error response as blow : 

/usr/local/lib/node_modules/dawn/node_modules/_console3@1.0.5@console3/lib/index.js:39
    let self = this;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dawn/bin/cli.js:8:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by Houfeng** [comment]
Node 版本是什么？

**Comment by Houfeng** [comment]
Dawn 需要 Node >=7.6.0

**Comment by lqjack** [comment]
thanks .
